apiVersion: ENC[AES256_GCM,data:I1A=,iv:YKdUaE1mnx0hQMCPJbac3lohwYOKig8JkrP3/5w9JEY=,tag:znC0EWgTOBFsTXSuHHSXnw==,type:str]
kind: ENC[AES256_GCM,data:R4MxAMMw,iv:L7OBn/2DOimeU3VzpkfbBL96BkAJ/34II9E95fo3PH0=,tag:scUoxezxfa0DOKdpTcxnUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DL9DFvNBLmIy/gMr8DclCNAQGQ7w6g==,iv:DIxPcqgtrkoTtWEh5T67OKWw0dHQYZYGzmA40LfWBfw=,tag:umrNnM6LDYgEqojbT33WCA==,type:str]
    namespace: ENC[AES256_GCM,data:ku28XjA8Cs4=,iv:TVx5kL2dwEr9z0eo31h4GD2jyOBuN+IKRIhqG5dbgFc=,tag:UZTiBQ27zFjM5SHHf8whkw==,type:str]
type: ENC[AES256_GCM,data:DtpFA5TN,iv:Dt2ab8jYeACu5PbBNavOPt7HxoQ6w8WtfusjnjkCfVQ=,tag:+HsFTnmnCJIsZNre0vvkeA==,type:str]
stringData:
    postgres-admin-password: ENC[AES256_GCM,data:ReQixhxK/+7TCEA0/PCp9y1JN9FyPg5z,iv:g71/6sPBZJM2S846PKapuZD1ZLvRSKpZgz99gHGgxBk=,tag:oAR7AQ0QF7uEOqU6BkHcaA==,type:str]
    postgres-password: ENC[AES256_GCM,data:imVi6owf0QvMqr00LJnDoD506gtm20Qi,iv:3bnDPAyBdbfOifQ1HUMcxm6WbViqbPeoeTGkSRZ7FLM=,tag:kRaXM18D/ZtvaRfBiYh4sw==,type:str]
    mongodb-passwords: ENC[AES256_GCM,data:m3PL9eYdX2NWy0CV12VZYAEY23dvKuL1,iv:mEksVxNg+b8OABPRjPzv7HL8al+YZ5q4hjJTaXPj2V8=,tag:Et9AIGoJPudIBEdNPcWu7g==,type:str]
    mongodb-root-password: ENC[AES256_GCM,data:JTmgO5yvKZWhnXT20KpQxpWOnC6wrTVG,iv:+aD5+SYa37M4LJ7k6HQZu1b4sdwl3RqUXiUmsXhOxY8=,tag:Foo1JGaUv4zCn0gJJpbeJg==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:nc2fN9/qII5N3lihEc1biboZhbc7slMp,iv:X5Bx4p1+1EKh2zbPMtf0OyM5pCbdVScYrY2QQ0sUUjs=,tag:qzowWqx4n3J8bAVepam9OQ==,type:str]
    rootUser: ENC[AES256_GCM,data:d/8oKPouCuP8Mw==,iv:Apo5DyzIaCGJ/8ewykmwzVhEjoInxvZteRJhfRI+1as=,tag:BLzXmJB87f3QgVKWevSN4Q==,type:str]
    rootPassword: ENC[AES256_GCM,data:lYfQbRmqSmpfXUHWu5eAywN/GJST9gBT,iv:sErCzlc2/6c9Sh5Y32+x9myVQdCn5mS6cnPvNxJ976g=,tag:Pq6jABjrL3Y0ktHboPoPNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d4lz2x5gzuuly0guqw6hnphcs6aq0x5em64ljhmkwf688tc6qdgsz4fs8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMzd1cWJFazkzaVlId3Rq
            ekZxWUJub0RtVGllYjNOUjFQK2RIYnBYN1FnCnlTeDd5cm9xVkNnYS9HUmYrR3p2
            ckNuVVpKM01DY0dORHV6WTBVYitqZk0KLS0tIHFOQktHSkhUR2FOUEV1T1JRVmt2
            YXlhbHFuZHlEZWl6eE1hRTQ2cVlmc0kKc2gQlFdrbwyC4GUsYYXIdSVBl518a7ce
            r2M0KdfEOhklo1s9nRaDCohUSTjiljzvCLMc98Qo0QEtaA5puJAjeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T20:23:32Z"
    mac: ENC[AES256_GCM,data:0XQeQ5F8uR70XZSfpuGaXe0eCJHvjHJwbU1bRB4vjpIGj/8NiC36XiMIDBH3fcYYQI6Jn0h+80IGHx/BfQxy1OYEwjnhcYlz8DvSDtBkVYyrUpClxk8q16UJKJutxSIf9+pvW+FgkZIjF+9L4KQ7Fea4a6ig+TtinT1eQwKIoqI=,iv:Rnwd/RC2tkt8/EpodeUU8yTvY490TSW13nxG+WtB9VU=,tag:i5I55/epFWhcJ6XgzOXAAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
