---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - infra-secrets.sops.yaml
  - postgresql.yaml
  - mongodb.yaml
  - redis.yaml
  - rabbitmq.yaml
  - qdrant.yaml
  - minio.yaml
  - ollama.yaml
