apiVersion: ENC[AES256_GCM,data:B4g=,iv:XwimhwA6lk/lx0+vumC6NR1yDxgLR+Z3w3UbyvsKAtY=,tag:Zm5eLLRB8SM9ThocM2c4CA==,type:str]
kind: ENC[AES256_GCM,data:+F9B3Lso,iv:/DLnXVD2X88CsAGEeBilHj3q1epLxFCEoVZva3kXnA4=,tag:h5z2IbgqteWiihtela5I8Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DpHPKut1YC0f7dtjsP2xqrc/,iv:FHU1jK7d4p/cUBR9d1ZmMUMk8hybM+TudUGnOYkpQ2c=,tag:YBHauhe77Orrcy1QzqbtvQ==,type:str]
    namespace: ENC[AES256_GCM,data:wcPFXYi0OxZG94rvD1iX,iv:1PZTFCEZMQA1ihTaCElE/arbf3p0muZC89MCNeGDa9I=,tag:pj3nNop6jairfFoVifBltQ==,type:str]
type: ENC[AES256_GCM,data:Lrso9RMk,iv:K7wzHRDQOi/7KGMcAeWR1wiYpYR5mKbCPVxn/C7sfh8=,tag:5hK2dyhiTPWRqXtlyWj9aw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:luoer5bq2EbuNw==,iv:s6NJDyqLTdM7q9cgB8WELtJ7b/F7BSwTF7/pW8iRwSo=,tag:InVrgrpbVEMdDqSZDyd2ZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9mz0lHwP62JNcjDNn6WZNYAb227UBgHF,iv:M16+uys/ut7U86j3qFRGKnic5piSr9EgRK0ebpfOUmM=,tag:dySZ8IUR3eW09rXhk33bwA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:V/+Y/0auwRY65/0i05f6bQFytIxBrRJFM3XljuAbV+OXZ38qAL3o8PdGrXY=,iv:OZrfPmu2TCUF4gc411KRHkHu9SsVZOp/IZ/kG/q/42A=,tag:Jtnv6JtUWWhaJkiEZHfd0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d4lz2x5gzuuly0guqw6hnphcs6aq0x5em64ljhmkwf688tc6qdgsz4fs8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY0xyaWJ4cTh5YWpnd1pO
            VFQ3NlBla0dlVWpzYUNZQzJCTnpGVmlRNVRZCmVtY0VrdUE1c3VhdWFmOTk5bDZq
            UFFrcVk2enpwSXhsOWQxVVFieksyaFEKLS0tIGhBbm9IKzV5ZDYvTDR2bXVxTnlI
            UGNnZ3RIOTZIRkc5bitRRG5xbldmSUUKWSOZB8Oiq5xLb9LFufb7ZyIWDnkgpd4G
            MB0FzT3VFT+3xPOhAz4K5XpIzMJad+vLLZkKm6O9Wv2ZWTkO1BORVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T11:35:06Z"
    mac: ENC[AES256_GCM,data:otbCQlKYKicmWKUcqN6hj6FIHP6BBHMi9IahsI8/ivhT2Xp+cW0VQnY5uuFdLk4DLJg3vZDWFszUOlB2X/YNN+I1liPrcxf8Fu74r/+Z21W361tl1cZE1sF76deu4Fzz9/mEK6dD/25Zv2Vhhgk+KH62R8CUx9aM6nZ4M21yQ8Y=,iv:Ej1+gOfAS3cOhwaUW99QMKOVzCIn3SkvebQW3NlThDY=,tag:O4nOdZtekdihDK96gkhKKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
