apiVersion: ENC[AES256_GCM,data:XeM=,iv:EYAULAYdyv0SPEhWfGlHOb4sEpV+5SwkPkKE+FtlSPc=,tag:x7D5B9+TlYkW30lNbG/Yww==,type:str]
kind: ENC[AES256_GCM,data:qJU+2T23,iv:p8LtMgUBbiOsvAAMi8PHKJo5dj61xN8KMUp/7BcVfO0=,tag:bcVp+64l2AWAhdJT0ccxXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EKvl0DJrDejDnBom8iZXGA==,iv:b0ao9RF1qLZgqxRg2H/9RvztGi9kWjjTXEhyHc0kS3Q=,tag:GylrDlSWA2hYOtFZTEPZ2g==,type:str]
    namespace: ENC[AES256_GCM,data:kTW0m5HGORc=,iv:xzqFdNs3syPJzIibUlCPEOFtaNqb1v+NMzvofxwUeJE=,tag:fVeKhSp2+Ft/3L2CU3sUPA==,type:str]
type: ENC[AES256_GCM,data:wI9DvQoa,iv:xWhIiBIRaq/nMocEoKGjWfuwASwHiRUO/ceLmKtme8E=,tag:UV7pJ6Q4LiJwOx4tkYWDYg==,type:str]
stringData:
    postgres-connection-string: ENC[AES256_GCM,data:UpDaAu6ImLapwWS0OcWJaJWKKDikqfwTclzK4PfUVHOfKzrHRDEK3xfiuSp1F3I56KOHZ6JeQm+laUl8SYiLHubnpGaiZBQn7nKmhYH7+xYXTI3W55mW31XY4N7pH3BgQoTOPTCGvBySsTEs4dVgyhQyElXU0AS6Ifw=,iv:3zxEz54mqfMWaLEVQ6SqTHTx6ejDsouY22NXNkT+FA0=,tag:vlPagpOV0J4yzOGQuTINVA==,type:str]
    jwt-signing-key: ENC[AES256_GCM,data:J76BK5Jv9fw9nTclwyMFAOz+lmJmubqh2to2bGf/9y161yoG1j8FqXs9UjqpQaaM,iv:Nulq9XFlmUk4KLtQsMyDUntMa8F7FTNM5iYSWjCH7ws=,tag:o5NlQJCVO1YP8itlelKEqw==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:+6IGwH640E3+cHbgzYrpcQftZ3bXp2C9,iv:Zn9P+tlwUL/9t8kLTWYxQmJaSnFrdQEEH0YqDFW57l0=,tag:Y0YQcNwtV7SC/osQP+RYBw==,type:str]
    grpc-api-key: ENC[AES256_GCM,data:P6SW8K5IZ4p2SGP0LAlgHLdge4KwyrE7t1rGRrHTUnE=,iv:LTJrYrTp1LFk1jCZnBKnPxI3jhsMhemAw4KdogkUy80=,tag:gJ12Hxg7eGHap2TV84pQeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d4lz2x5gzuuly0guqw6hnphcs6aq0x5em64ljhmkwf688tc6qdgsz4fs8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YkdRc1lCV2cwVSt3ZnVO
            T3NtcmFvaXNIOGRwM3NjYVdBaytHSk9TTkM0Cm9sNXJsYTliSWU4VktURldaRmdB
            SFUxOWFoSGpxUVJmaEt5Z00rTGI0VWsKLS0tIGI3WTEyOTl5dzZaQnllZElMYnMr
            Nk80bDRjU3N2WURCcVlXNGM3WWUxenMKDW+xvY0cScS9REXVIbkjfBv6hHY47LYx
            q3FMC+GkouCfAdb5jrrxZPmyBYq6YiUGdqkDa4vXIp/IrVubT+aNqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T20:23:44Z"
    mac: ENC[AES256_GCM,data:ChkWAkZoSjyAdumb4F0Yeo7jxXbme5Oo9Yhu1L0xaMzif4XjawiEC0J5mdPW/NaOrlrdlgiOTYtTjTy9z1y4U/xRXbO54WhuZkmu8ArcfUlY/wZj8+cslS0jkkEd1v5lBksABOKd+ZLm1FWZAoYxpH9fbH740CbzfNdkseSbt98=,iv:+MtthxJ73zPsgwDq+HnQ88V3R20Yryrl5cEjflyLhY0=,tag:X1BboSWcVXOGEIrYIVSdmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
