apiVersion: ENC[AES256_GCM,data:v2w=,iv:C1H7qqIV2du/hIhAAReEpeJEck8EKaIRJP+q3b4QmdE=,tag:1brodKBd8We5vfVhGSD4ew==,type:str]
kind: ENC[AES256_GCM,data:mHCtTJvn,iv:G3FkzqzW2yiLmB/cJ4xz0Mri8WSMxVNCUT8nPa4Z+ko=,tag:PXQNXXt6QBfTKsngrKiZwA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s5GdidGSqdoRooTMTJT9lwA8CO1a+6pl,iv:CbOY9TZ35/+L1IJZ2BYfYSRH5oKy7OcGj4CPSC1Ymsg=,tag:BN5rDItgHq+5AzurImDkXw==,type:str]
    namespace: ENC[AES256_GCM,data:gfZQaScOvxyC+3s=,iv:wQNblpSD71uXu9TZhpVX9iUAfBbTwT7GnvIGGLNBhGY=,tag:KH6vECqtkWXrD2eZGgPW+A==,type:str]
type: ENC[AES256_GCM,data:di5ZanUx,iv:iOnCbReDnIH1nuqQSyjBWOXiVNlFsItv+TDmNoJDqto=,tag:11eBwUjDBFN5cN9ZOfe6Ew==,type:str]
stringData:
    token: ENC[AES256_GCM,data:Q3FSvyV1WL5VWJAdimZCR0NRRRwDxnOx1xiCCdNj+OuEOTbvOVusoWgxRDynoyf9lYTq518ZdKgcsr2Nh38XyyzRCg031WkrG2ff2o0GxfD+VRKzfUM1NyId0EaxbwjWUYto/jFJbXjTtnQQMUHaZR9yCHXaibxuh5IEULbbF6w6NXy+95qQjArIfVX4m0M8w6RP5FIw4sSQhV4sCiEr4/tQUzUE+YCb6WxRgEfbYu1rQonlU4nkxA==,iv:a+lr77Hvc2jXbOHQAZL2M9Oad6hZKrpy/F1+ZgQ9p1o=,tag:7o4OAgtY9K612vKdnS+1Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d4lz2x5gzuuly0guqw6hnphcs6aq0x5em64ljhmkwf688tc6qdgsz4fs8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YStDS0UzY3oxdDVzTytO
            RkRUU0VGOGlicnFNNWZFNnZTV1YybmgvcVZBCk1oNFFnRG9YQ1VVdTJDSTRhbkZ5
            QkxMY2lCeEMwK1kvRDQyMU5yY0pPMkkKLS0tIE0wZm1vMVo5NytzUHJHZURObmxE
            MUl3dGc4Rm84azVqUFlMN04zeXN3cHcKyjQ8J8OWjib+Yb67Qlna1WCTj00e2hng
            KC/PpoHj1i6/vVbFUj4zNtSuzKf7kVQo/wxWpgnz1/0uvyWA6fIhNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T17:28:14Z"
    mac: ENC[AES256_GCM,data:7cNyJgQDRx1UGJzlapUAqMIH1L+6J72VXGsp4sL0Nri40GH2ptUMMK3hnmMmDMLABK1HjcUWEIOJ6km/6aVdXg+m7t9soyudTI+FNLCOWz+3NkGF/B1Olv0ykwDlZhozR5lOXvQ245G+qY3DQIaM4dpg/62mnak7kAzPzQBwzBg=,iv:MtbAwpwalXX9FVvuwmzu8dylPAz76zMFjBF/IMBIBNo=,tag:sf3PUrI9UPVhEAxmkYb3Bg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
